<?php
$settings = array(
	array('name' => "General", 'parent' => 'CiviCRM',
	  'desc' => "Any Wikimedia specific issues. After they have been confirmed as core issues .. they should be moved to the core CiviCRM bug tracker.",
	  'owner' => "arichards\x40wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
	array('name' => "jheora", 'parent' => 'Cortado',
	  'desc' => "Theora (video) decoder",
	  'owner' => "tstarling\x40wikimedia.org",
	  'cc' => ""),
array('name' => "jorbis", 'parent' => 'Cortado',
	  'desc' => "Vorbis (audio) decoder",
	  'owner' => "tstarling\x40wikimedia.org",
	  'cc' => ""),
array('name' => "JST", 'parent' => 'Cortado',
	  'desc' => "Stream manager",
	  'owner' => "tstarling\x40wikimedia.org",
	  'cc' => ""),
array('name' => "User interface", 'parent' => 'Cortado',
	  'desc' => "Cortado user interface",
	  'owner' => "tstarling\x40wikimedia.org",
	  'cc' => ""),
	array('name' => "General", 'parent' => 'dbzip2',
	  'desc' => "General issues with dbzip2",
	  'owner' => "brion\x40wikimedia.org",
	  'cc'   => "brion\x40wikimedia.org"),
	array('name' => "API", 'parent' => 'Mediawiki',
	  'desc' => "MediaWiki\'s bot API, accessible via api.php",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "Bryan.TongMinh\x40Gmail.com, roan.kattouw\x40gmail.com, sam\x40reedyboy.net, soxred93\x40gmail.com, vasilvv\x40gmail.com"),
array('name' => "Blocking",'parent' => 'Mediawiki',
	  'desc' => "Blocking, unblocking, all that stuff",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Categories",'parent' => 'Mediawiki',
	  'desc' => "All issues relating to categories.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Change Tagging",'parent' => 'Mediawiki',
	  'desc' => "Issues with revision/log/change tags added by edit filters (AbuseFilter, TorBlock, etc).",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org"),
array('name' => "Database",'parent' => 'Mediawiki',
	  'desc' => "Back-end database issues: SQL errors, compatibility, etc.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Deleting",'parent' => 'Mediawiki',
	  'desc' => "Issues related to deleting and undeleting/restoring pages and revisions (via action=delete and Special:Undelete).",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Device compatibility",'parent' => 'Mediawiki',
	  'desc' => "Bug reports related to use cases that do not give expected output for MediaWiki pages output devices like web browsers, printers, or speakers.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "DjVu",'parent' => 'Mediawiki',
	  'desc' => "All issues related to DjVu",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Documentation",'parent' => 'Mediawiki',
	  'desc' => "All documentation, including that on MediaWiki.org",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Email",'parent' => 'Mediawiki',
	  'desc' => "Issues relating to the email notification features and email address verification (Special:Confirmemail etc.)",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Export/Import",'parent' => 'Mediawiki',
	  'desc' => "Issues relating to Special:Export and Special:Import",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "General/Unknown",'parent' => 'Mediawiki',
	  'desc' => "All issues that did not fit into any of the other components.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "History/Diffs",'parent' => 'Mediawiki',
	  'desc' => "All issues relating to the page displaying an article\'s history and the page displaying differences between two revisions.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Images and files",'parent' => 'Mediawiki',
	  'desc' => "Image and uploaded file management (thumbnails etc.)",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "Bryan.TongMinh\x40Gmail.com"),
array('name' => "Installation",'parent' => 'Mediawiki',
	  'desc' => "Installation, setup, and upgrade procedure.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "innocentkiller\x40gmail.com"),
array('name' => "Internationalization",'parent' => 'Mediawiki',
	  'desc' => "All issues relating to internationalization, localization, translation, and the MediaWiki namespace.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Javascript",'parent' => 'Mediawiki',
	  'desc' => "MediaWiki\'s Javascript infrastructure",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "tparscal\x40wikimedia.org"),
array('name' => "Language converter",'parent' => 'Mediawiki',
	  'desc' => "Script conversion for Chinese and Serbian.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "PhiLiP.NPC\x40Gmail.com"),
array('name' => "Maintenance scripts",'parent' => 'Mediawiki',
	  'desc' => "Command-line maintenance scripts for various tasks.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "innocentkiller\x40gmail.com"),
array('name' => "Modern skin",'parent' => 'Mediawiki',
	  'desc' => "The \"Modern\" skin.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "r.tarnell\x40IEEE.ORG"),
array('name' => "Page editing",'parent' => 'Mediawiki',
	  'desc' => "All issues relating to the edit screen, edit conflicts, and saving edits.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Page protection",'parent' => 'Mediawiki',
	  'desc' => "Protection and unprotection of pages, and issues with protected pages",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Parser",'parent' => 'Mediawiki',
	  'desc' => "Issues relating to the process that converts wiki syntax into HTML.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Recent changes",'parent' => 'Mediawiki',
	  'desc' => "Bug reports and feature requests related to the special page RecentChanges.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Redirects",'parent' => 'Mediawiki',
	  'desc' => "All issues relating to redirects.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Resource Loader",'parent' => 'Mediawiki',
	  'desc' => "The resource loader that handles page resources, such as CSS and Javascript",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "roan.kattouw\x40gmail.com, tparscal\x40wikimedia.org"),
array('name' => "Revision deletion",'parent' => 'Mediawiki',
	  'desc' => "Hiding and unhiding of individual page revisions, log entries and usernames and revision suppression.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "aschulz4587\x40gmail.com"),
array('name' => "Search",'parent' => 'Mediawiki',
	  'desc' => "Issues relating to the search engine. Note that Wikimedia web sites do not use the default MediaWiki search engine; please file bugs against the Lucene Search component in the Extensions product instead.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Special pages",'parent' => 'Mediawiki',
	  'desc' => "All special pages (Wanted pages, Orphans, etc.). Recent changes and Watchlist have their own component.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Syndication",'parent' => 'Mediawiki',
	  'desc' => "MediaWiki\'s handling of RSS and Atom feeds",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Templates",'parent' => 'Mediawiki',
	  'desc' => "All issues relating to templates and template inclusion.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Unit tests",'parent' => 'Mediawiki',
	  'desc' => "Unit testing suite, based on PHPUnit",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "mah\x40everybody.org"),
array('name' => "Uploading",'parent' => 'Mediawiki',
	  'desc' => "File upload interface at Special:Upload",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "Bryan.TongMinh\x40Gmail.com"),
array('name' => "User interface",'parent' => 'Mediawiki',
	  'desc' => "Issues relating to the user interface and skins, including Monobook, Classic, Nostalgia, Cologne Blue, DaVinci, etc.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "User login",'parent' => 'Mediawiki',
	  'desc' => "Account creation, login, etc.\r\n\r\nSettings bugs in this component should be migrated to the User preferences component.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "User preferences",'parent' => 'Mediawiki',
	  'desc' => "All issues relating to user preferences (please migrate user settings bugs in the User login/settings component to this one)",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org"),
array('name' => "Vector Skin",'parent' => 'Mediawiki',
	  'desc' => "The Vector skin",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "asharma\x40wikimedia.org, tparscal\x40wikimedia.org"),
array('name' => "Watchlist",'parent' => 'Mediawiki',
	  'desc' => "Bug reports and feature requests related to the special page Watchlist.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "general",'parent' => 'mwdumper',
	  'desc' => "Anything that doesn\'t fit somewhere else",
	  'owner' => "brion\x40wikimedia.org",
	  'cc' => ""),
array('name' => "GUI",'parent' => 'mwdumper',
	  'desc' => "The Swing graphical user interface",
	  'owner' => "brion\x40wikimedia.org",
	  'cc' => ""),
array('name' => "Add media wizard",'parent' => 'MWEmbed',
	  'desc' => "The \x3ca href=\"http://www.mediawiki.org/wiki/Extension:Add_Media_Wizard\">add media wizard\x3c/a> supports searching repositories, inline uploading and basic resource transformations for inline inserting of media into articles",
	  'owner' => "dale\x40ucsc.edu",'parent' => 'MWEmbed',
	  'cc' => ""),
array('name' => "Firefogg",'parent' => 'MWEmbed',
	  'desc' => "Firefogg is the firefox browser extension that we use for client side transcoding of video and chunked uploads of large media files.",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
array('name' => "General/Unknown",'parent' => 'MWEmbed',
	  'desc' => "Bugs relatated to mwEmbed that cannot be categorised or should still be categorised.",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
array('name' => "Script loader",'parent' => 'MWEmbed',
	  'desc' => "The \x3ca href=\"http://www.mediawiki.org/wiki/ScriptLoader\">script loader\x3c/a> localises, packages and gzips multiple JavaScript files in a single request.",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
array('name' => "Sequence editor",'parent' => 'MWEmbed',
	  'desc' => "The \x3ca href=\"http://www.mediawiki.org/wiki/Extension:Sequencer\">Sequencer editor\x3c/a> is a in-browser video editor.",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
array('name' => "Timed text",'parent' => 'MWEmbed',
	  'desc' => "These correspond to bugs around video timed text parsing display, and editing.",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
array('name' => "Video player",'parent' => 'MWEmbed',
	  'desc' => "The JavaScript player used for embedded video playback",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
	array('name' => "AcaWiki",'parent' => 'Wikimedia',
	  'desc' => "AcaWiki site migration and setup issues.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Blog",'parent' => 'Wikimedia',
	  'desc' => "\x3ca href=\"http://blog.wikimedia.org\">Wikimedia Blog\x3c/a>",
	  'owner' => "gpaumier\x40wikimedia.org",
	  'cc' => ""),
array('name' => "Bugzilla",'parent' => 'Wikimedia',
	  'desc' => "Configuration problems with MediaWiki\'s Bugzilla bug tracker.\r\n\r\nNOTE: Please don\'t report bugs in the underlying Bugzilla system. Those bugreports should go to http://bugzilla.mozilla.org/ !",
	  'owner' => "mhershberger\x40wikimedia.org",
	  'cc' => "innocentkiller\x40gmail.com, sam\x40reedyboy.net"),
array('name' => "DNS",'parent' => 'Wikimedia',
	  'desc' => "Issues relating to the nameserver configuration.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Downloads",'parent' => 'Wikimedia',
	  'desc' => "Public data dumps at download.wikimedia.org",
	  'owner' => "tfinc\x40wikimedia.org",
	  'cc' => ""),
array('name' => "Extension setup",'parent' => 'Wikimedia',
	  'desc' => "New extensions to get installed or enabled. Just like \'Site request\' but more specific.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Fundraising - misc",'parent' => 'Wikimedia',
	  'desc' => "A catch-all for miscellaneous fundraising-related components not covered by mediawiki extensions and civicrm",
	  'owner' => "arichards\x40wikimedia.org",
	  'cc' => ""),
array('name' => "Fundraising Requirements",'parent' => 'Wikimedia',
	  'desc' => "User stories for the annual fundraiser",
	  'owner' => "tfinc\x40wikimedia.org",
	  'cc' => ""),
array('name' => "General/Unknown",'parent' => 'Wikimedia',
	  'desc' => "All issues that don\'t not fit into any of the other components.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Interwiki links",'parent' => 'Wikimedia',
	  'desc' => "Inter-language and inter-wiki links.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "IRC",'parent' => 'Wikimedia',
	  'desc' => "Issues with the irc.wikimedia.org Recent Changes feeds and bot tools on irc.freenode.net not covered elsewhere.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Language setup",'parent' => 'Wikimedia',
	  'desc' => "New languages or fixes to language settings.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "lucene-search-2",'parent' => 'Wikimedia',
	  'desc' => "Issues with the lucene-search-2 backend.",
	  'owner' => "rainman\x40EUnet.rs",
	  'cc' => ""),
array('name' => "Mailing lists",'parent' => 'Wikimedia',
	  'desc' => "Issues relating to the mailing lists at http://mail.wikipedia.org/",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "OTRS",'parent' => 'Wikimedia',
	  'desc' => "Wikimedia\'s OTRS service and setup",
	  'owner' => "tstarling\x40wikimedia.org",
	  'cc' => ""),
array('name' => "Prototype server",'parent' => 'Wikimedia',
	  'desc' => "Bugs relating to the test deployments at prototype.wikimedia.org",
	  'owner' => "roan.kattouw\x40gmail.com",
	  'cc' => "pdhanda\x40wikimedia.org"),
array('name' => "Site logos",'parent' => 'Wikimedia',
	  'desc' => "Problem with any Wikimedia project site logos",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Site requests",'parent' => 'Wikimedia',
	  'desc' => "Requests for config changes for the sites hosted by the Wikimedia Foundation.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "SSL related",'parent' => 'Wikimedia',
	  'desc' => "Issues about https://secure.wikimedia.org/ , HTTPS site wide or SSL certificates.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Subversion",'parent' => 'Wikimedia',
	  'desc' => "Wikimedia-operated Subversion server and repositories",
	  'owner' => "rlane32\x40gmail.com",
	  'cc' => "innocentkiller\x40gmail.com"),
array('name' => "Testing Infrastructure",'parent' => 'Wikimedia',
	  'desc' => "\x3ca href=\"http://ci.tesla.usability.wikimedia.org/cruisecontrol/index\">Cruise Control\x3c/a>, \x3ca href=\"toolserver.org/~krinkle/testswarm\">Test Swarm\x3c/a> etc etc",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Usage Statistics",'parent' => 'Wikimedia',
	  'desc' => "The usage statistics at http://stats.wikimedia.org/",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "User survey",'parent' => 'Wikimedia',
	  'desc' => "For issues relating to the general Wikipedian user survey.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "WAP mobile gateway",'parent' => 'Wikimedia',
	  'desc' => "WAP interface for mobile access at *.wap.wikipedia.org",
	  'owner' => "tstarling\x40wikimedia.org",
	  'cc' => ""),
array('name' => "wikibugs IRC bot",'parent' => 'Wikimedia',
	  'desc' => "wikibugs, the IRC bug spamming script",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "code-utils",'parent' => 'Wikimedia Tools',
	  'desc' => "Various PHP code utilities like check-vars.php and stylize.php",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "PhotoCommons",'parent' => 'Wikimedia Tools',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/PhotoCommons\">PhotoCommons\x3c/a> WordPress Extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "huskyr\x40gmail.com, krinklemail\x40gmail.com"),
array('name' => "WikiSnaps",'parent' => 'Wikimedia Tools',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/WikiSnaps\">WikiSnaps\x3c/a> iPhone app",
	  'owner' => "hartman\x40videolan.org",
	  'cc' => ""),
array('name' => "[Other]",'parent' => 'Wikimedia Tools',
	  'desc' => "All other tools not covered by a specific product",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "android",'parent' => 'Wikipedia mobile',
	  'desc' => "Wikipedia mobile Android application",
	  'owner' => "preilly\x40wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
array('name' => "iphone",'parent' => 'Wikipedia mobile',
	  'desc' => "Wikipedia mobile iPhone application",
	  'owner' => "preilly\x40wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
array('name' => "server",'parent' => 'Wikipedia mobile',
	  'desc' => "Mobile Server",
	  'owner' => "preilly\x40wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
array('name' => "General",'parent' => 'XML Snapshots',
	  'desc' => "Any issues related to dumpHTML should be moved to MediaWiki extensions. Issues for MW export should go to Import/Export\r\n\r\nOtherwise they should go here.",
	  'owner' => "ariel\x40wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
array('name' => "ABC", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:ABC\">ABC\x3c/a> extension",
	  'owner' => "r.tarnell\x40IEEE.ORG",
	  'cc' => ""),
array('name' => "AbsenteeLandlord", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:AbsenteeLandlord\">AbsenteeLandlord\x3c/a> extension",
	  'owner' => "t.laqua\x40gmail.com",
	  'cc' => ""),
array('name' => "AbuseFilter", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:AbuseFilter\">AbuseFilter\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org"),
array('name' => "ActiveAbstract", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:ActiveAbstract\">ActiveAbstract\x3c/a> extension",
	  'owner' => "jeluf\x40gmx.de",
	  'cc' => "brion\x40wikimedia.org"),
array('name' => "AddMediaWizard", 'parent' => 'MediaWiki Extensions',
	  'desc' => "AddMediaWizard Extension",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
array('name' => "AdminLinks", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Admin_Links\">AdminLinks\x3c/a> extension",
	  'owner' => "yaron57\x40gmail.com",
	  'cc' => ""),
array('name' => "AdvancedMeta", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Advanced_Meta\">AdvancedMeta\x3c/a> Extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "AdvancedRandom", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The AdvancedRandom special page extension.",
	  'owner' => "avarab\x40gmail.com",
	  'cc' => ""),
array('name' => "AdvancedSearch", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:AdvancedSearch\">AdvancedSearch\x3c/a> extension",
	  'owner' => "roan.kattouw\x40gmail.com",
	  'cc' => ""),
array('name' => "AjaxLogin", 'parent' => 'MediaWiki Extensions',
	  'desc' => "AjaxLogin extension allows users to log in through an AJAX pop-up box. Instead of being taken to Special:UserLogin when they click \"Log in / Register\", an AJAX pop-up box will be presented to them.",
	  'owner' => "jack\x40countervandalism.net",
	  'cc' => "korczynski\x40gmail.com"),
array('name' => "AntiSpoof", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Username similarity checker; rejects spoofed usernames on registration.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "soxred93\x40gmail.com"),
array('name' => "APC", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:APC\">APC\x3c/a> extension",
	  'owner' => "niklas.laxstrom\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "ApiSandbox", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:ApiSandbox\">ApiSandbox\x3c/a> Extension",
	  'owner' => "maxsem.wiki\x40gmail.com",
	  'cc' => "sam\x40reedyboy.net"),
array('name' => "ArticleFeedback", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Issues related to the \x3ca>ArticleFeedback\x3c/a> extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "dtaraborelli\x40wikimedia.org, krinklemail\x40gmail.com, roan.kattouw\x40gmail.com"),
array('name' => "AskSQL", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The AskSQL special page extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Babel", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Babel\">Babel\x3c/a> extension",
	  'owner' => "robert\x40rhl.me.uk",
	  'cc' => ""),
array('name' => "BackAndForth", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The BackAndForth extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "BadImages", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Bad Image List extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "BookManager", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:BookManager\">BookManager\x3c/a> extension",
	  'owner' => "raylton.sousa\x40gmail.com",
	  'cc' => ""),
array('name' => "BotQuery", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The bot query API (query.php)",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "CategoryOnUpload", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:CategoryOnUpload\">CategoryOnUpload\x3c/a> extension",
	  'owner' => "robert\x40rhl.me.uk",
	  'cc' => ""),
array('name' => "CategoryStepper", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:CategoryStepper\">CategoryStepper\x3c/a> extension",
	  'owner' => "robert\x40rhl.me.uk",
	  'cc' => ""),
array('name' => "CategoryTree", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:CategoryTree\">CategoryTree\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "brightbyte\x40gmail.com"),
array('name' => "CentralAuth", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Wikimedia\'s unified login extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org, vasilvv\x40gmail.com"),
array('name' => "CentralNotice", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Centralised notice extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "rkaldari\x40wikimedia.org"),
array('name' => "CharInsert", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The CharInsert extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "brion\x40wikimedia.org"),
array('name' => "CheckUser", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The CheckUser special page extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "aschulz4587\x40gmail.com"),
array('name' => "Cite", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The \x3ca href=\"http://meta.wikimedia.org/wiki/Cite\">Cite\x3c/a> special page and parser hook extensions.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "CLDR", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:CLDR\">CLDR\x3c/a> extension",
	  'owner' => "niklas.laxstrom\x40gmail.com",
	  'cc' => ""),
array('name' => "CodeReview", 'parent' => 'MediaWiki Extensions',
	  'desc' => "CodeReview extension for SVN post-commit review.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "innocentkiller\x40gmail.com, sam\x40reedyboy.net"),
array('name' => "Collection", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Page collection extension for PDF/ODT generation via PediaPress\'s mwlib backend. Primarily for the Special:Book frontend. Note there is an \x3ca href=\"http://code.pediapress.com/wiki/report\">upstream bug tracker\x3c/a> maintained by PediaPress folks separately.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "development\x40pediapress.com"),
array('name' => "Configure", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Configure\">Configure extension\x3c/a> to MediaWiki",
	  'owner' => "ialex.wiki\x40gmail.com",
	  'cc' => ""),
array('name' => "ConfirmAccount", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:ConfirmAccount\">ConfirmAccount\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "aschulz4587\x40gmail.com"),
array('name' => "ConfirmEdit (CAPTCHA extension)", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The ConfirmEdit CAPTCHA extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "ContributionReporting", 'parent' => 'MediaWiki Extensions',
	  'desc' => "ContributionStatistics, ContributionTrackingStatistics, FundraiserStats",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
array('name' => "ContributionScores", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Contribution_Scores\">ContributionScores\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "t.laqua\x40gmail.com"),
array('name' => "ContributionTracking", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Fundraising information tracking/display frontend.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
array('name' => "Contributors", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Contributors extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "CooperationStatistics", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:CooperationStatistics\">CooperationStatistics\x3c/a> extension",
	  'owner' => "alfred.maghi\x40gmail.com",
	  'cc' => ""),
array('name' => "CountEdits", 'parent' => 'MediaWiki Extensions',
	  'desc' => "CountEdits extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "CrossNamespaceLinks", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The CrossNamespaceLinks special page extension.",
	  'owner' => "avarab\x40gmail.com",
	  'cc' => ""),
array('name' => "CustomUserSignup", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:CustomUserSignup\">http://www.mediawiki.org/wiki/Extension:CustomUserSignup\x3c/a>",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "ngautam\x40wikimedia.org"),
array('name' => "DataTransfer", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Data_Transfer\">DataTransfer\x3c/a> extension",
	  'owner' => "yaron57\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "DeletedContributions", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The DeletedContributions extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "DeleteQueue", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:DeleteQueue\">DeleteQueue\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org"),
array('name' => "Desysop", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Desysop extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "DidYouMean", 'parent' => 'MediaWiki Extensions',
	  'desc' => "DidYouMean experimental extension",
	  'owner' => "hippytrail\x40gmail.com",
	  'cc' => ""),
array('name' => "DiscussionThreading", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:DiscussionThreading\">DiscussionThreading\x3c/a> extension",
	  'owner' => "jack.pond\x40psitex.com",
	  'cc' => ""),
array('name' => "DismissableSiteNotice", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Dismissable Site Notice extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "DonationInterface", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Modular payment gateway with support for PayPal.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "arichards\x40wikimedia.org, tfinc\x40wikimedia.org"),
array('name' => "DoubleWiki", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The DoubleWiki extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Drafts", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Drafts\">Drafts\x3c/a> extension",
	  'owner' => "tparscal\x40wikimedia.org",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "DumpHTML", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Static HTML dump generator extension component",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
array('name' => "DynamicPageList", 'parent' => 'MediaWiki Extensions',
	  'desc' => "DynamicPageList extension (not DynamicPageList2, which is not in use at Wikimedia)",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "bawolff+wn\x40gmail.com"),
array('name' => "DynamicPageList2", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Dynamic page list. Two!",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "EasyTimeline", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The EasyTimeline extension.",
	  'owner' => "erikzachte\x40infodisiac.com",
	  'cc' => ""),
array('name' => "Edit Messages", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:EditMessages\">Edit Messages\x3c/a> extension",
	  'owner' => "tstarling\x40wikimedia.org",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "Editcount", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Editcount special page extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Eval", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Eval special page extension.",
	  'owner' => "avarab\x40gmail.com",
	  'cc' => ""),
array('name' => "ExpandTemplates", 'parent' => 'MediaWiki Extensions',
	  'desc' => "ExpandTemplates extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "ExtensionDistributor", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:ExtensionDistributor\">ExtensionDistributor\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "Extensions requests", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Requests for new extensions.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "External editors", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Manual:External_editors\">External editors\x3c/a>",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "FCKeditor", 'parent' => 'MediaWiki Extensions',
	  'desc' => "FCKeditor WYSIWYG extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "FlaggedRevs", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:FlaggedRevs\">FlaggedRevs\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "aschulz4587\x40gmail.com, asharma\x40wikimedia.org, innocentkiller\x40gmail.com, pdhanda\x40wikimedia.org, robla\x40wikimedia.org"),
array('name' => "FootNote", 'parent' => 'MediaWiki Extensions',
	  'desc' => "FootNote extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "FundraiserPortal", 'parent' => 'MediaWiki Extensions',
	  'desc' => "FundraiserPortal extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "tparscal\x40wikimedia.org"),
array('name' => "Gadgets", 'parent' => 'MediaWiki Extensions',
	  'desc' => "User-organized JavaScript gadgets extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "brightbyte\x40gmail.com, krinklemail\x40gmail.com, maxsem.wiki\x40gmail.com"),
array('name' => "General/Unknown", 'parent' => 'MediaWiki Extensions',
	  'desc' => "All issues that did not fit into any of the other components.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "GeoLite", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Geo redirection service",
	  'owner' => "tfinc\x40wikimedia.org",
	  'cc' => ""),
array('name' => "GIS", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The GIS extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "GlobalBlocking", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:GlobalBlocking\">GlobalBlocking\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org"),
array('name' => "GlobalUsage", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:GlobalUsage\">GlobalUsage\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "Bryan.TongMinh\x40Gmail.com"),
array('name' => "Glossary", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Glossary\">Glossary extension\x3c/a> (not maintained in Wikimedia SVN)",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "GoogleMaps", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Google_Maps\">GoogleMaps\x3c/a> extension",
	  'owner' => "emmiller\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "GroupPermissionsManager", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:GroupPermissionsManager\">GroupPermissionsManager\x3c/a> extension",
	  'owner' => "skizzerz\x40gmail.com",
	  'cc' => ""),
array('name' => "Highlight", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Highlight parser hook extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "ImageMap", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:ImageMap\">ImageMap\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "ImportFreeImages", 'parent' => 'MediaWiki Extensions',
	  'desc' => "ImportFreeImages extension",
	  'owner' => "Bryan.TongMinh\x40Gmail.com",
	  'cc' => ""),
array('name' => "IndexFunction", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:IndexFunction\">IndexFunction extension\x3c/a>",
	  'owner' => "mrzmanwiki\x40gmail.com",
	  'cc' => ""),
array('name' => "InlineEditor", 'parent' => 'MediaWiki Extensions',
	  'desc' => "InlineEditor Extension",
	  'owner' => "jp.posma\x40gmail.com",
	  'cc' => ""),
array('name' => "InlineScripts", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Victor\'s InlineScripts extension",
	  'owner' => "vasilvv\x40gmail.com",
	  'cc' => ""),
array('name' => "Inputbox", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:InputBox\">InputBox\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Interlanguage", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Interlanguage\">Interlanguage\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "Interwiki (extension)", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Interwiki\">Interwiki\x3c/a> extension",
	  'owner' => "soxred93\x40gmail.com",
	  'cc' => ""),
array('name' => "Invitations", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Invitations\">Invitations\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org"),
array('name' => "LabeledSectionTransclusion", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Labeled_Section_Transclusion\">Labeled section transclusion\x3c/a> extension to MediaWiki",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "ssanbeg\x40web.de"),
array('name' => "LanguageSelector", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:LanguageSelector\">LanguageSelector\x3c/a> extension",
	  'owner' => "brightbyte\x40gmail.com",
	  'cc' => ""),
array('name' => "LinkSearch", 'parent' => 'MediaWiki Extensions',
	  'desc' => "LinkSearch extension",
	  'owner' => "brion\x40wikimedia.org",
	  'cc' => ""),
array('name' => "LiquidThreads", 'parent' => 'MediaWiki Extensions',
	  'desc' => "LiquidThreads advanced discussion extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org, bharris\x40wikimedia.org"),
array('name' => "LiveTranslate", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Live_Translate\">LiveTranslate\x3c/a> extension",
	  'owner' => "jeroen_dedauw\x40yahoo.com",
	  'cc' => ""),
array('name' => "LocalisationUpdate", 'parent' => 'MediaWiki Extensions',
	  'desc' => "LocalisationUpdate",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "tom.maaswinkel\x4012wiki.eu"),
array('name' => "LogEntry", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:LogEntry\">LogEntry\x3c/a> extension",
	  'owner' => "tparscal\x40wikimedia.org",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "LookupUser", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:LookupUser\">LookupUser\x3c/a> extension",
	  'owner' => "tstarling\x40wikimedia.org",
	  'cc' => ""),
array('name' => "Lua", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Lua\">Lua\x3c/a> extension",
	  'owner' => "fran\x40dumetella.net",
	  'cc' => ""),
array('name' => "Lucene Search", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Lucene Search extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "rainman\x40EUnet.rs"),
array('name' => "Maintenance", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Maintenance\">Maintenance\x3c/a> extension",
	  'owner' => "mediawiki\x40ryandesign.com",
	  'cc' => ""),
array('name' => "Makebot", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Special:Makebot extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Makesysop", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Makesysop special page extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Maps", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Maps\">Maps\x3c/a> extension",
	  'owner' => "jeroen_dedauw\x40yahoo.com",
	  'cc' => ""),
array('name' => "Math (texvc)", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The texvc module which renders &lt;math&gt; formulae.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "MediaFunctions", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:MediaFunctions\">MediaFunctions\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "MetadataEdit", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:MetadataEdit\">MetadataEdit\x3c/a> extension",
	  'owner' => "ialex.wiki\x40gmail.com",
	  'cc' => ""),
array('name' => "MetaVidWiki", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Semantic video goodness!",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
array('name' => "MobileFrontend", 'parent' => 'MediaWiki Extensions',
	  'desc' => "PHP extension for mobile gateway",
	  'owner' => "preilly\x40wikimedia.org",
	  'cc' => "tfinc\x40wikimedia.org"),
array('name' => "MostRevisors", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:MostRevisors\">MostRevisors\x3c/a> extension",
	  'owner' => "alfred.maghi\x40gmail.com",
	  'cc' => ""),
array('name' => "MultiBoilerplate", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:MultiBoilerplate\">MultiBoilerplate\x3c/a> extension",
	  'owner' => "robert\x40rhl.me.uk",
	  'cc' => ""),
array('name' => "MultiUpload", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:MultiUpload\">MultiUpload \x3c/a> extension",
	  'owner' => "tderouin\x40gmail.com",
	  'cc' => ""),
array('name' => "MWSearch", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:MWSearch\">MWSearch\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "rainman\x40EUnet.rs"),
array('name' => "Narayam", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Narayam\">Narayam\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "junu.pv\x40gmail.com"),
array('name' => "NewestPages", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The NewestPages extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "robchur\x40gmail.com"),
array('name' => "Newuserlog", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Newuserlog extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "NewUserNotif", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:New User Email Notification\">New User Email Notification\x3c/a> extension",
	  'owner' => "jack.pond\x40psitex.com",
	  'cc' => ""),
array('name' => "Nogomatch", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Nogomatch logging extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "NSFileRepo", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:NSFileRepo\">NSFileRepo\x3c/a> extension",
	  'owner' => "jack.pond\x40psitex.com",
	  'cc' => ""),
array('name' => "Nuke", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Nuke special page extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "OAI", 'parent' => 'MediaWiki Extensions',
	  'desc' => "OAI-PMH repository and harvester",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "brion\x40wikimedia.org"),
array('name' => "OggHandler", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Ogg metadata & player extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "OmegaWiki", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.omegawiki.org\">OmegaWiki\x3c/a> website (using Wikidata)",
	  'owner' => "robert\x40rhl.me.uk",
	  'cc' => ""),
array('name' => "OnlineStatus", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:OnlineStatus\">OnlineStatus\x3c/a> extension",
	  'owner' => "ialex.wiki\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "OpenID", 'parent' => 'MediaWiki Extensions',
	  'desc' => "OpenID extension",
	  'owner' => "mail\x40tgries.de",
	  'cc' => ""),
array('name' => "OpenSearchXml", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:OpenSearchXml\">OpenSearchXml\x3c/a> extension",
	  'owner' => "brion\x40wikimedia.org",
	  'cc' => ""),
array('name' => "OpenStackManager", 'parent' => 'MediaWiki Extensions',
	  'desc' => "OpenStackManager extension",
	  'owner' => "rlane32\x40gmail.com",
	  'cc' => ""),
array('name' => "Oversight", 'parent' => 'MediaWiki Extensions',
	  'desc' => "HideRevision and other Oversight components",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "brion\x40wikimedia.org"),
array('name' => "PackageForce", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:PackageForce\">PackageForce\x3c/a> extension",
	  'owner' => "svippy\x40gmail.com",
	  'cc' => ""),
array('name' => "PageCSS", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The PageCSS parser hook extension.",
	  'owner' => "avarab\x40gmail.com",
	  'cc' => ""),
array('name' => "PagedTiffHandler", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:PagedTiffHandler\">PagedTiffHandler\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "glaser\x40hallowelt.biz"),
array('name' => "PageNotice", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:PageNotice\">PageNotice\x3c/a> extension",
	  'owner' => "brightbyte\x40gmail.com",
	  'cc' => ""),
array('name' => "ParserFunctions", 'parent' => 'MediaWiki Extensions',
	  'desc' => "ParserFunctions extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "PasswordReset", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:PasswordReset\">PasswordReset\x3c/a> extension",
	  'owner' => "t.laqua\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "Patroller", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Patroller extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "PdfHandler", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:PdfHandler\">PdfHandler\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Poem", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Poem\">Poem\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "ssanbeg\x40web.de"),
array('name' => "Poll", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Poll extension",
	  'owner' => "jan\x40jans-seite.de",
	  'cc' => ""),
array('name' => "PoolCounter", 'parent' => 'MediaWiki Extensions',
	  'desc' => "PoolCounter Extension",
	  'owner' => "Platonides\x40gmail.com",
	  'cc' => "tstarling\x40wikimedia.org"),
array('name' => "Postcomment", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Postcomment\">Postcomment\x3c/a> extension",
	  'owner' => "tderouin\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "Preloader", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Preloader extension in Subversion",
	  'owner' => "robchur\x40gmail.com",
	  'cc' => ""),
array('name' => "ProofreadPage", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Proofread_Page\">ProofreadPage\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "thomasV1\x40gmx.de"),
array('name' => "QPoll", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:QPoll\">QPoll extension\x3c/a>",
	  'owner' => "questpc\x40rambler.ru",
	  'cc' => ""),
array('name' => "Quiz", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Quiz extension for MediaWiki",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "RandomImage", 'parent' => 'MediaWiki Extensions',
	  'desc' => "RandomImage extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "ReaderFeedback", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:ReaderFeedback\">ReaderFeedback\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "aschulz4587\x40gmail.com"),
array('name' => "RecordAdmin", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:RecordAdmin\">Extension:RecordAdmin\x3c/a> - A special page for finding and editing record articles using forms",
	  'owner' => "aran\x40organicdesign.co.nz",
	  'cc' => ""),
array('name' => "RefHelper", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:RefHelper\">RefHelper\x3c/a> extension",
	  'owner' => "jonwilliford\x40gmail.com",
	  'cc' => ""),
array('name' => "RefreshSpecial", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:RefreshSpecial\">RefreshSpecial\x3c/a> extension",
	  'owner' => "jack\x40countervandalism.net",
	  'cc' => ""),
array('name' => "RegexBlock", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:RegexBlock\">RegexBlock\x3c/a> extension",
	  'owner' => "bartek\x40wikia-inc.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "Renameuser", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Renameuser special page extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "aschulz4587\x40gmail.com"),
array('name' => "ReplaceText", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Replace_Text\">ReplaceText\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "yaron57\x40gmail.com"),
array('name' => "RSS", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:RSS\">RSS\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "brightbyte\x40gmail.com, jack\x40countervandalism.net, jeroen_dedauw\x40yahoo.com, mah\x40everybody.org"),
array('name' => "ScanSet", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The ScanSet parser hook extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "SecurePoll", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The SecurePoll extension, which supercedes the older BoardVote extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "tstarling\x40wikimedia.org"),
array('name' => "SelectCategory", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:SelectCategory\">SelectCategory extension\x3c/a> to MediaWiki",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "leon\x40leonweber.de"),
array('name' => "Semantic MediaWiki", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Semantic MediaWiki extension",
	  'owner' => "markus\x40semantic-mediawiki.org",
	  'cc' => "jeroen_dedauw\x40yahoo.com"),
array('name' => "SemanticDrilldown", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Semantic_Drilldown\">Semantic Drilldown extension\x3c/a> for navigating semantic data.",
	  'owner' => "yaron57\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "SemanticForms", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Semantic Forms extension for Semantic MediaWiki",
	  'owner' => "yaron57\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "SemanticFormsInputs", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Semantic_Forms_Inputs\">SemanticFormsInputs\x3c/a> extension",
	  'owner' => "f.trott\x40gmx.net",
	  'cc' => ""),
array('name' => "SemanticMaps", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Semantic_Maps\">Semantic Maps\x3c/a> extension",
	  'owner' => "jeroen_dedauw\x40yahoo.com",
	  'cc' => ""),
array('name' => "SemanticResultFormats", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Contrib code for Semantic MediaWiki extensions.",
	  'owner' => "jeroen_dedauw\x40yahoo.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org, yaron57\x40gmail.com"),
array('name' => "SharedUserRights", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:SharedUserRights\">SharedUserRights\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "charlie\x40mudoo.net, lgarczewski\x40gmail.com"),
array('name' => "SimpleSecurity", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:SimpleSecurity\">SimpleSecurity extension\x3c/a>",
	  'owner' => "aran\x40organicdesign.co.nz",
	  'cc' => ""),
array('name' => "SiteMatrix", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Wikimedia site matrix",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "SlippyMaps", 'parent' => 'MediaWiki Extensions',
	  'desc' => "SlippyMaps extension and related components. See maps-l mailing list.",
	  'owner' => "avarab\x40gmail.com",
	  'cc' => "aude.wiki\x40gmail.com"),
array('name' => "SmoothGallery", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:SmoothGallery\">SmoothGallery\x3c/a> extension",
	  'owner' => "rlane32\x40gmail.com",
	  'cc' => ""),
array('name' => "SocialProfile", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:SocialProfile\">SocialProfile\x3c/a> extension",
	  'owner' => "jack\x40countervandalism.net",
	  'cc' => ""),
array('name' => "Sort", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Sort extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Spam Blacklist", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Spam blacklist extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "StringFunctionsEscaped", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:StringFunctionsEscaped\">StringFunctionsEscaped\x3c/a> extension",
	  'owner' => "jack.pond\x40psitex.com",
	  'cc' => ""),
array('name' => "SyntaxHighlight (GeSHi)", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Syntax highlighting parser hook extension using the GeSHi highlighting engine",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "soxred93\x40gmail.com"),
array('name' => "Tasks", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Tasks extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Throttle", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The Throttle extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "TimedMediaHandler", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:TimedMediaHandler\">TimedMediaHandler\x3c/a> extension",
	  'owner' => "dale\x40ucsc.edu",
	  'cc' => ""),
array('name' => "TitleBlacklist", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Title blacklist extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "vasilvv\x40gmail.com"),
array('name' => "TitleKey", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:TitleKey\">TitleKey\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "brion\x40wikimedia.org"),
array('name' => "TorBlock", 'parent' => 'MediaWiki Extensions',
	  'desc' => "TorBlock extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "agarrett\x40wikimedia.org"),
array('name' => "Translate", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Translate\">Translate\x3c/a> extension",
	  'owner' => "niklas.laxstrom\x40gmail.com",
	  'cc' => "s.mazeland\x40xs4all.nl"),
array('name' => "UniversalEditButton", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:UniversalEditButton\">UniversalEditButton\x3c/a> extension",
	  'owner' => "brion\x40wikimedia.org",
	  'cc' => ""),
array('name' => "Uniwiki", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Category:Uniwiki\">Uniwiki\x3c/a> extension collection",
	  'owner' => "robert\x40rhl.me.uk",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "UploadWizard", 'parent' => 'MediaWiki Extensions',
	  'desc' => "UploadWizard provides a multi-file, step-by-step JavaScript wizard to\r\nupload multimedia files to a MediaWiki website (Special:UploadWizard).",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "asharma\x40wikimedia.org, neilk\x40wikimedia.org"),
array('name' => "UsabilityInitiative", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Issues related to the extensions developed by the \x3ca href=\"http://usability.wikimedia.org\">Wikimedia Usability Initiative\x3c/a> ( EditWarning, PrefStats, ClickTracking, etc.). Bugs for Vector and/or WikiEditor should be reported in their own components!",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "asharma\x40wikimedia.org, roan.kattouw\x40gmail.com, tparscal\x40wikimedia.org"),
array('name' => "UsageStatistics", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://mediawiki.org/wiki/Extension:Usage_Statistics\">UsageStatistics\x3c/a> extension",
	  'owner' => "gri6507\x40yahoo.com",
	  'cc' => "alfred.maghi\x40gmail.com"),
array('name' => "UserMerge", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:UserMerge\">UserMerge\x3c/a> Extension",
	  'owner' => "mail\x40tgries.de",
	  'cc' => ""),
array('name' => "UsernameBlacklist", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Username Blacklist extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "UserRightsNotif", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:User_Rights_Email_Notification\">UserRightsNotif\x3c/a> extension",
	  'owner' => "Abigor\x40forgotten-beauty.com",
	  'cc' => ""),
array('name' => "Vector", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Vector\">Vector\x3c/a> Extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "roan.kattouw\x40gmail.com, tparscal\x40wikimedia.org"),
array('name' => "WebFonts", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:WebFonts\">WebFonts\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "WhiteList", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:WhiteList\">WhiteList\x3c/a> extension",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Widgets", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Widgets\">Widgets\x3c/a> extension",
	  'owner' => "sergey.chernyshev\x40gmail.com",
	  'cc' => "wikibugs-l\x40lists.wikimedia.org"),
array('name' => "WikiBhasha", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:WikiBhasha\">WikiBhasha\x3c/a> extension to aide in translation of articles",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "s.mazeland\x40xs4all.nl, WBMSRI\x40microsoft.com"),
array('name' => "Wikidata", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Wikidata",
	  'owner' => "robert\x40rhl.me.uk",
	  'cc' => ""),
array('name' => "wikidiff2", 'parent' => 'MediaWiki Extensions',
	  'desc' => "C++ diff engine used on Wikimedia",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "tstarling\x40wikimedia.org"),
array('name' => "WikiEditor", 'parent' => 'MediaWiki Extensions',
	  'desc' => "WikiEditor extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "roan.kattouw\x40gmail.com, tparscal\x40wikimedia.org"),
array('name' => "WikiHiero", 'parent' => 'MediaWiki Extensions',
	  'desc' => "The WikiHiero (hieroglyphics) extension.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => ""),
array('name' => "Wikilog", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:Wikilog\">Wikilog\x3c/a> extension",
	  'owner' => "bugs\x40juliano.info",
	  'cc' => ""),
array('name' => "WikiLove", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Extension for adding positive feedback on user talk pages.",
	  'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "rkaldari\x40wikimedia.org"),
array('name' => "WikiTextLoggedInOut", 'parent' => 'MediaWiki Extensions',
	  'desc' => "\x3ca href=\"http://www.mediawiki.org/wiki/Extension:WikiTextLoggedInOut\">WikiTextLoggedInOut\x3c/a> extension",
	  'owner' => "jack\x40countervandalism.net",
	  'cc' => ""),
array('name' => "[other]", 'parent' => 'MediaWiki Extensions',
	  'desc' => "Other extensions not in the list",
	 'owner' => "wikibugs-l\x40lists.wikimedia.org",
	  'cc' => "")
);

$admin = array(
"agarrett@wikimedia.org",
"brion@wikimedia.org",
"hashar@free.fr",
"innocentkiller@gmail.com",
"krinklemail@gmail.com",
"mah@everybody.org",
"r.tarnell@IEEE.ORG",
"rhalsell@wikimedia.org",
"rlane32@gmail.com",
"roan.kattouw@gmail.com",
"robla@robla.net",
"robla@wikimedia.org",
"s.mazeland@xs4all.nl",
"sam@reedyboy.net",
"tfinc@wikimedia.org",
"tstarling@wikimedia.org",
);

$people = array();

function incr($p) {
	global $people;

	if( !isset($people[$p]) ) {
		$people[$p] = 1;
	} else {
		$people[$p]++;
	}
}

foreach($settings as $b) {
	$n = $b['parent']."/".$b['name'];
	$mod[$n] = $b['desc'];
	$owner[$b['owner']][] = $n;
	incr($b['owner']);
	foreach(preg_split("/, */", $b['cc']) as $c) {
		if($c) {
			$cc[$c][] = $n;
			incr($c);
		}
	}
}

$non_admin_body = "
As the Bugmeister for Wikimedia, one of the things I am doing right
now is cleaning up CC lists and default assigments on the various
components that we track in Bugzilla (see
http://bugzilla.wikimedia.org/).

Your email is listed as the default owner or a member of the default
CC list of one or more components in Bugzilla.  Please respond to this
message to let me know which of these emails you want to continue
getting.  If I do not hear from you by August 1st, I will remove you
from the following place(s):

";

$admin_body = "
Since you are listed as an admin by Bugzilla, I'll assume that you
have the ability to add or remove yourself from the following areas of
Bugzilla.  This email is simply a reminder.

";

asort($people);
foreach($people as $n => $c) {
	if ($n !== "wikibugs-l@lists.wikimedia.org" ) {
		$headers = "To: $n\r\nFrom: Mark A. Hershberger <mhershberger@wikimedia.org>\r\nSubject: Email from Wikimedia's Bugzilla\r\n";
		$email = "";
		$isAdmin = in_array($n, $admin);

		if($isAdmin) {
			$email .= $admin_body;
		} else {
			$email .= $non_admin_body;
		}

		if(isset($owner[$n]))
			foreach($owner[$n] as $m) {
				$email .= "  Owner of $m\n";
			}

		if(isset($cc[$n]))
			foreach($cc[$n] as $m) {
				$email .= "  CC on $m\n";
			}

		if(!$isAdmin) {
			$email .= "
Again, please let me know by August 1st which, if any, of these you
would like to keep.
";
		}

		$email .= "
Thanks,

Mark A. Hershberger
Bugmeister
Wikimedia Foundation
mhershberger@wikimedia.org
717.271.1084
";

		mail( $n, "Email from Wikimedia's Bugzilla", $email, $headers, "-f mhershberger@wikipedia.org" );
		file_put_contents("email/$n", $email);

	}
}
